### ISSUE TITLE
bash on windows

### ISSUE THREAD

**Issue by elge70** [debugloop/telescope-undo.nvim#14]
use_delta = true,
            side_by_side = true,
            layout_strategy = 'vertical',
            layout_config = {
                preview_height = 0.8,
            },

does not work on windows even if delta is present. 

**if opts.use_delta and vim.fn.executable("bash") == 1 and vim.fn.executable("delta") == 1 then in previewers.lua** may be the issue. Windows has bash but it will spawn WSL. If you could invoke delta without bash it may work.

**Comment by debugloop** [comment]
I'm calculating the diff internally using nvim's own facilities. The external program is only used as a formatter, i.e. it receives the patch format diff on stdin, which is why bash (or really any shell with pipes) is required.

If you're interested in fixing this I'm willing to support you with any questions you might have, but I don't have access to or interest in WSL myself. I'll look into detecting WSL and avoiding using an external diff viewer in any case though.

**Comment by debugloop** [comment]
For now, I've added some code to detect WSL and use no external diff formatter in that case.
