### ISSUE TITLE
[Request] Fold code around x lines away from the diff?

### ISSUE THREAD

**Issue by Ajaymamtora** [debugloop/telescope-undo.nvim#56]
When In a long file where the diffs are somewhere far from the top of the file, I have to manually scroll down loads until I find the diff. It would be great if the picker only showed 5 or 6 lines around where the diff is like Github and IntelliJ do so I don't have to scroll and can just see the changes as I go down the items in the picker.

e.g. this is where the previewer is initially at the top of the file:
![image](https://github.com/user-attachments/assets/9f2c3d84-477a-434e-92e3-7f6ace17cdd5)

but the diff is on line 739:
![image](https://github.com/user-attachments/assets/19d894eb-14bf-4a66-9550-a7fd1660990c)

An alternative could be that the first diff is always initially focused, and allow a keymap to jump to next/prev diff? This way no fancy code is needed to calculate where to fold etc

**Comment by debugloop** [comment]
What you describe happens if you have a large `scrolloff` configured, you can override using `scrolloff` by using the following config piece in your `opts`.

```lua
vim_diff_opts = {
  ctxlen = vim.o.scrolloff,
},
```

Currently, this plugin does not parse the diff at all, we literally take it from the builtin diff to `delta` and display that in a terminal. So, both your suggestions would need the fancy code implemented to even interpret diffs. The issue with autoscrolling to a change came up before though, with the question being which changed line to scroll to, if there are multiple locations (search and replace, ...). So I like you're suggestion of keymaps, but still I'll probably not implement the required fancy code there 😬

I'm open to a PR though, if you still think it's worth it after configuring `ctxlen` 👍🏻
