### ISSUE TITLE
Changing telescope config not applied

### ISSUE THREAD

**Issue by snikoletopoulos** [debugloop/telescope-undo.nvim#60]
I'm using lazy.nvim. I change the `undo` configuration in the `opts` settings of telescope (ex. use_delta & mappings).
However, no change are applied when I use the plugin.

Am I doing something wrong here?

telescope-undo.nvim config:
```lua
{
  "debugloop/telescope-undo.nvim",
  lazy = true,
  specs = {
    {
      "nvim-telescope/telescope.nvim",
      dependencies = {
        "debugloop/telescope-undo.nvim",
        {
          "AstroNvim/astrocore",
          opts = {
            mappings = {
              n = {
                ["<Leader>fu"] = { "<Cmd>Telescope undo<CR>", desc = "Find undos" },
              },
            },
          },
        },
      },
      opts = function() require("telescope").load_extension "undo" end,
    },
  },
}
```

telescope config:
```lua
{
  "nvim-telescope/telescope.nvim",
  opts = {
    extensions = {
      undo = {
        use_delta = false,
      },
    },
  },
}
```

**Comment by zbindenren** [comment]
Same issue here:,I have the default config

```lua
{
  "debugloop/telescope-undo.nvim",
  dependencies = { -- note how they're inverted to above example
    {
      "nvim-telescope/telescope.nvim",
      dependencies = { "nvim-lua/plenary.nvim" },
    },
  },
  keys = {
    { -- lazy style key map
      "<leader>u",
      "<cmd>Telescope undo<cr>",
      desc = "undo history",
    },
  },
  opts = {
    -- don't use `defaults = { }` here, do this in the main telescope spec
    extensions = {
      undo = {
        -- telescope-undo.nvim config, see below
      },
      -- no other extensions here, they can have their own spec too
    },
  },
  config = function(_, opts)
    -- Calling telescope's setup from multiple specs does not hurt, it will happily merge the
    -- configs for us. We won't use data, as everything is in it's own namespace (telescope
    -- defaults, as well as each extension).
    require("telescope").setup(opts)
    require("telescope").load_extension("undo")
  end,
},
```

<c-r> creates an empty file named `state #2, -1, 2 weeks ago`

**Comment by debugloop** [comment]
Hi, I'm pretty sure you are 🫠 After spending some time on it I can only conclude it's about the use of `specs` which I do not fully understand w.r.t. the order of calls to the `setup` methods.

But there seems to be more wrong with your snippets:
1. This appears to build an cyclic dependency. `telescope-undo` -> `telescope` -> `telescope-undo` (which gets merged with the toplevel anyhow, continuing...). Lazy apparently handles this smartly.
2. If `opts` is a function (it is here), it's return value will replace all previous `opts` (see lazy docs). Since your `opts` function does not return anything, it might replace the opts from the top-level telescope config.
3. I'm personally not always clear on when `<cmd>Bla` is evaluated and thus prefer to use direct function calls myself, i.e. `function() require("telescope").extensions.undo.undo() end` instead of your RHS string. This ensures the require/undo call is evaluated when the key is pressed, but maybe the string form works in the same way.

I'm going to close this, but feel free to reopen with a minimal example, and ideally a counter example of a telescope plugin which works where `telescope-undo` does not, in your preferred way of configuring.
