### ISSUE TITLE
Option to set diff program

### ISSUE THREAD

**Issue by brneor** [debugloop/telescope-undo.nvim#7]
Can we have an option to specify which `diff` program to use so we can point it to [difftastic](https://github.com/Wilfred/difftastic)?

**Comment by debugloop** [comment]
I've implemented a way to set a custom command, as outlined in the README. Please tell me if you get `difftastic` to work using this option, because I couldn't:

This plugin uses the internal diff facilities and uses delta only as a formatter. I don't think `difftastic` has the ability to do that? Using external diff tools for the actual diffing would mean a whole mess of temporary files.

**Comment by brneor** [comment]
I also couldn't get it working. I'll have a better look at difftastic's docs and report back as soon as I can.
